import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { CalculationResults, SnCurveParams, AnalysisParams } from '../types';

export const generatePdfReport = (
  results: CalculationResults,
  snParams: SnCurveParams,
  durationSeconds: number,
  projectName: string = "Fatigue Analysis Report"
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // -- HEADER --
  doc.setFillColor(49, 46, 129); // Indigo 900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("FatigueLife Pro", 14, 20);
  
  doc.setFontSize(10);
  doc.text("Spectral Fatigue Analysis Report (Wirsching Method)", 14, 30);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' });
  doc.text(`v2.0.0`, pageWidth - 14, 30, { align: 'right' });

  let yPos = 55;

  // -- SUMMARY SECTION --
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(14);
  doc.text("1. Analysis Summary", 14, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.text("This report details the spectral fatigue damage calculation based on the Wirsching & Light method.", 14, yPos);
  yPos += 6;
  doc.text("The method corrects Narrow Band approximation conservatism for wide-band PSD inputs.", 14, yPos);

  // -- RESULTS BOX --
  yPos += 15;
  doc.setFillColor(245, 247, 250); // Slate 50
  doc.setDrawColor(200, 200, 200);
  doc.rect(14, yPos, pageWidth - 28, 45, 'FD');
  
  doc.setFontSize(11);
  doc.setTextColor(79, 70, 229); // Indigo 600
  doc.text("CALCULATED LIFE (WIRSCHING)", 20, yPos + 10);
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  const lifeHours = results.wirschingLifeSeconds / 3600;
  doc.text(`${lifeHours.toExponential(3)} Hours`, 20, yPos + 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Total Damage (D): ${results.wirschingDamage.toExponential(4)}`, 20, yPos + 30);
  doc.text(`Exposure Duration: ${(durationSeconds/3600).toFixed(2)} Hours`, 100, yPos + 30);
  doc.text(`RMS Stress: ${results.rmsStress.toFixed(2)} MPa`, 100, yPos + 20);

  yPos += 55;

  // -- INPUT PARAMETERS TABLE --
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(14);
  doc.text("2. Input Parameters", 14, yPos);
  
  yPos += 5;
  (doc as any).autoTable({
    startY: yPos,
    head: [['Parameter', 'Value', 'Description']],
    body: [
      ['S-N Slope (m)', snParams.m.toString(), 'Material Fatigue Slope'],
      ['S-N Constant (K)', snParams.K.toExponential(3), 'Material Constant (N*S^m = K)'],
      ['Exposure', `${(durationSeconds/3600).toFixed(2)} hrs`, 'Duration of the random event'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229] },
  });

  // -- SPECTRAL STATISTICS TABLE --
  yPos = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text("3. Spectral Statistics", 14, yPos);
  
  yPos += 5;
  (doc as any).autoTable({
    startY: yPos,
    head: [['Metric', 'Value', 'Unit']],
    body: [
      ['Zero Crossings (v0)', results.expectedZeroCrossings.toFixed(2), 'Hz'],
      ['Expected Peaks (Ep)', results.expectedPeaks.toFixed(2), 'Hz'],
      ['Irregularity Factor', results.irregularityFactor.toFixed(4), '-'],
      ['Spectral Width (epsilon)', results.spectralWidth.toFixed(4), '-'],
      ['m0 (Variance)', results.m0.toExponential(4), '(MPa)^2'],
      ['m2 (Moment)', results.m2.toExponential(4), '(MPa)^2 * Hz^2'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [100, 116, 139] }, // Slate 500
  });

  // -- FOOTER --
  const totalPages = doc.getNumberOfPages();
  for(let i = 1; i <= totalPages; i++) {
     doc.setPage(i);
     doc.setFontSize(8);
     doc.setTextColor(150);
     doc.text(`Page ${i} of ${totalPages} - Generated by FatigueLife Pro`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save("Fatigue_Analysis_Report.pdf");
};
